name: Test Docs compile

on:
  pull_request:
    branches:
      - main
    paths:
      - Docs/**
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test Docs compile
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Docs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Docs/package-lock.json
          
      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build